### ISSUE TITLE
Ломается при загрузке

### ISSUE THREAD

**Issue by vice-versa** [animalnots/Procurement-RUS#2]
Прокьюремент 2.2.0 Инициализирован.

Авторизация chucknorris                                                                   [OK]
Призываем героев...                                                                       

[Error] Ожидается состояние "Element".. Обнаружен "Text" с именем "", пространство имен "". 

После этого останавливается.

update: Ломается так когда у тебя устарела кука, надо видимо как то более осознано ругаться, типа не могу авторизоваться, проверьте актуальность куки.

**Comment by animalnots** [comment]
Исправим в ближайшее время.

**Comment by animalnots** [comment]
Исправлено
